/**
 * builderLabels — Extract builder labels from translation object.
 *
 * Maps LABELS.builder.* to a flat object for Alpine scope.
 */

export function pickBuilderLabels(L: {
  builder: Record<string, string>;
}) {
  const b = L.builder;
  return {
    saveSession: b.saveSession,
    editSaveSession: b.editSaveSession,
    collapseAll: b.collapseAll,
    expandAll: b.expandAll,
    noExoAdded: b.noExoAdded,
    noExoDesc: b.noExoDesc,
    needName: b.needName,
    needExo: b.needExo,
    needSets: b.needSets,
    emptyLibrary: b.emptyLibrary,
    createExoLink: b.createExoLink,
    allAdded: b.allAdded,
    noSearchMatch: b.noSearchMatch,
    addExoAria: b.addExoAria,
    toSession: b.toSession,
    showTipAria: b.showTipAria,
    seeTechnique: b.seeTechnique,
    videoAria: b.videoAria,
    onYoutube: b.onYoutube,
    supersetLabel: b.supersetLabel,
    supersetFor: b.supersetFor,
    newSuperset: b.newSuperset,
    supersetRemove: b.supersetRemove,
    setsFor: b.setsFor,
    setTypeLabel: b.setTypeLabel,
    weightForSet: b.weightForSet,
    repsForSet: b.repsForSet,
    deleteSet: b.deleteSet,
    noSets: b.noSets,
    setsPlural: b.setsPlural,
    setsSingular: b.setsSingular,
    warmupTitle: b.warmupTitle,
    warmupHint: b.warmupHint,
    warmupBtn: b.warmupBtn,
    fatigueOn: b.fatigueOn,
    fatigueOutOf5: b.fatigueOutOf5,
    moodLabel: b.moodLabel,
    moodGreat: b.moodGreat,
    moodGood: b.moodGood,
    moodOk: b.moodOk,
    moodTired: b.moodTired,
    moodBad: b.moodBad,
    discardConfirm: b.discardConfirm,
    top: b.top,
    units: b.units,
    discardTitle: b.discardTitle,
    mrvSuggestFor: b.mrvSuggestFor,
    mrvNoHistory: b.mrvNoHistory,
    mrvFromHistory: b.mrvFromHistory,
    mrvCapped: b.mrvCapped,
    mrvToast: b.mrvToast,
    removeExerciseTitle: b.removeExerciseTitle,
    setTypeHeader: b.setTypeHeader,
    weightHeader: b.weightHeader,
    fatigueTitle: b.fatigueTitle,
    fatigueAria: b.fatigueAria,
    moodTitle: b.moodTitle,
    notesLabel: b.notesLabel,
    pickerTitle: b.pickerTitle,
    tipTitle: b.tipTitle,
    videoTitle: b.videoTitle,
  };
}
